version: 2
jobs:
  puppetlabs_spec_ruby25:
    docker:
      - image: cimg/ruby:2.5
    steps:
      - checkout
      - run: bundle install
      - run: bundle exec rake
  puppetlabs_spec_ruby27:
    docker:
      - image: cimg/ruby:2.7
    steps:
      - checkout
      - run: bundle install
      - run: bundle exec rake
  puppetlabs_spec_ruby3:
    docker:
      - image: cimg/ruby:3.0
    steps:
      - checkout
      - run: bundle install
      - run: bundle exec rake
  puppetlabs_spec_ruby31:
    docker:
      - image: cimg/ruby:3.1
    steps:
      - checkout
      - run: bundle install
      - run: bundle exec rake
  puppetlabs_spec_ruby32:
    docker:
      - image: cimg/ruby:3.2
    steps:
      - checkout
      - run: bundle install
      - run: bundle exec rake

workflows:
  version: 2
  test:
    jobs:
      - puppetlabs_spec_ruby25
      - puppetlabs_spec_ruby27
      - puppetlabs_spec_ruby3
      - puppetlabs_spec_ruby31
      - puppetlabs_spec_ruby32
